name: Notify CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  notify:
    if: github.repository_owner == 'equinor'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Create repository dispatch event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/equinor/witsml-explorer-equinor/dispatches \
            -d '{"event_type":"mergedispatch ${{ github.ref_name }}","client_payload":{"branch": "${{ github.ref_name }}", "version":"latest"}}'
