name: Dispatch tag updates to CICD repo

on:
  push:
    tags:
      - 'rips-wex*'

jobs:
  fetchtag:
    runs-on: ubuntu-latest  
    if: github.ref_type == 'tag'
    steps:
      - id: get
        run: |
          VERSION_ONLY=$(echo "${{ github.ref_name }}" | cut -d '@' -f2)
          echo "tag-version=$VERSION_ONLY" >> $GITHUB_OUTPUT
    outputs:
      tag-version: ${{ steps.get.outputs.tag-version }}            

  notify:
    if: github.repository_owner == 'equinor'
    needs: fetchtag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create repository dispatch event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/equinor/witsml-explorer-equinor/dispatches \
            -d '{"event_type":"tagdispatch ${{ github.ref_name }}","client_payload":{"tag": "${{ github.ref_name }}", "version":"${{ needs.fetchtag.outputs.tag-version }}"}}'

          
